# Config Server Port
server.port=8888

# Application Name
spring.application.name=config-server

# GitHub Repository URL
spring.cloud.config.server.git.uri=https://github.com/PritishSingh13/microservices-config

# Optional but recommended (helps during development)
spring.cloud.config.server.git.clone-on-start=true

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka